 name: Send Email
  if: steps.notify.outputs.url != ''
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 587
    username: ${{ secrets.EMAIL_USER }}
    password: ${{ secrets.EMAIL_PASS }}
    subject: "🚨 New Issue in care_fe"
    body: |
      A new unassigned issue has been created.

      Title: ${{ steps.notify.outputs.title }}
      Link: ${{ steps.notify.outputs.url }}
    to: aravindswamymajjuri143@gmail.com, kadaripavani1@gmail.com
    from: GitHub Issue Bot <aravindswamymajjuri143@gmail.com>
    
