
name: Email Alert for New Issues

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check new issues in original repo
        uses: actions/github-script@v7
        with:
          script: |
            const owner = "ohcnetwork";
            const repo = "care_fe";

            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: "open",
              sort: "created",
              direction: "desc",
              per_page: 1
            });

            const issue = issues.data[0];

            if (issue && !issue.assignee) {
              core.exportVariable("SEND_EMAIL", "true");
              core.exportVariable("ISSUE_TITLE", issue.title);
              core.exportVariable("ISSUE_URL", issue.html_url);
            } else {
              core.exportVariable("SEND_EMAIL", "false");
            }

      - name: Send Email
        if: env.SEND_EMAIL == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🚨 New Issue in care_fe"
          body: |
            A new unassigned issue has been created.

            Title: ${{ env.ISSUE_TITLE }}
            Link: ${{ env.ISSUE_URL }}
          to: aravindswamymajjuri143@gmail.com, kadaripavani1@gmail.com
          from: GitHub Issue Bot <aravindswamymajjuri143@gmail.com>
          
